# Generated by Django 5.0.2 on 2024-02-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='product_images/')),
                ('image2', models.ImageField(upload_to='product_images/')),
                ('image3', models.ImageField(upload_to='product_images/')),
                ('image4', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('product_brand', models.CharField(max_length=255)),
                ('age_category', models.CharField(max_length=20)),
                ('in_stock', models.BooleanField(default=True)),
                ('colors', models.ManyToManyField(blank=True, to='app.color')),
            ],
        ),
    ]
